tap "nikitabobko/tap"

# Terminal Stuff
brew "bat"
brew "colima"
brew "coreutils"
brew "delta"
brew "docker"
brew "docker-compose"
brew "entr"
brew "fd"
brew "ffmpeg"
brew "gh"
brew "git"
brew "gpg"
brew "grep"
brew "fzf"
brew "libpq", link: true
brew "llama.cpp"
brew "lynx"
brew "macos-trash"
brew "mpv"
brew "node"
brew "ollama"
brew "openshift-cli"
brew "pandoc"
brew "pass"
brew "plantuml"
brew "rename"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "streamlink"
brew "telnet"
brew "tmux"
brew "tmuxinator"
brew "universal-ctags"
brew "uv"
brew "vim"
brew "vivid"
brew "wget"
brew "yt-dlp"

# Apps
cask "microsoft-edge"
cask "dbeaver-community"
cask "visual-studio-code"
cask "iterm2"
cask "wacom-tablet"
cask "logitech-camera-settings"
cask "rectangle"
cask "obs"
cask "dteoh-devdocs"
cask "basictex"
cask "figma"
cask "aerospace"

# Fonts
cask "font-hack-nerd-font"

# VSCode extensions

vscode "aidenoah.punk-hacking"
vscode "bierner.markdown-mermaid"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "charliermarsh.ruff"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "maattdd.gitless"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-edgedevtools.vscode-edge-devtools"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.live-server"
vscode "orta.vscode-jest"
vscode "ryanluker.vscode-coverage-gutters"
vscode "streetsidesoftware.code-spell-checker"
vscode "streetsidesoftware.code-spell-checker-canadian-english"
vscode "vscodevim.vim"
