#!/bin/sh

ln -sf "${PWD}/.bashrc" "${HOME}/.bashrc"
ln -sf "${PWD}/.profile" "${HOME}/.profile"
ln -sf "${PWD}/.tmux.conf" "${HOME}/.tmux.conf"
ln -sf "${PWD}/.vimrc" "${HOME}/.vimrc"
ln -sf "${PWD}/.zprofile" "${HOME}/.zprofile"
ln -sf "${PWD}/.zshrc" "${HOME}/.zshrc"
ln -sf "${PWD}/.lynx.cfg" "${HOME}/.lynx.cfg"

mkdir -p "${HOME}/.bin"
ln -sf "${PWD}/bin/duck" "${HOME}/.bin/duck"
ln -sf "${PWD}/bin/dot_session" "${HOME}/.bin/dot_session"

if [ "$1" != "" ]
then
  sh "./machines/$1/setup"
fi
