# Ergonomics
brew "bat"                                # Ergonomic cat.
brew "chawan"                             # A usable terminal web browser
brew "curl"                               # For wcurl
brew "delta"                              # Ergonomic diff.
brew "eza"                                # Ergonomic ls replacement.
brew "fd"                                 # Ergonomic alternative to find.
brew "fish"                               # Ergonomic shell.
brew "fzf"                                # General fuzzy finder.
brew "gh"                                 # Github client.
brew "git"                                # More up to date than xcode git.
brew "helix"                              # Trying this new editor.
brew "macos-trash"                        # Trash, instead of delete, files.
brew "rename"                             # Bulk renaming.
brew "ripgrep"                            # More ergonomic grep.
brew "starship"                           # Zero config prompt.
brew "vivid"                              # Generate sane LS_COLORS
brew "zoxide"                             # Ergonomic cd.

# Development Tools
brew "entr"                               # Run processes on file change.
brew "docker"                             # For when I want a container.
brew "docker-compose"                     # Ditto.

# Services
brew "ollama"                             # Run LLMs.
brew "syncthing"                          # Sync files
brew "colima"                             # Containerd runtime

# LSPs
brew "markdown-oxide"                     # md

# Formatters
brew "prettier"                           # js, css, md, html, gql, yaml

# Other Tools
brew "exiftool"                           # Used in photo renaming.
brew "ffmpeg"                             # Video and Audio manipulation.
brew "newsraft"                           # RSS readere
brew "stow"                               # I use this to manage dotfiles.
brew "streamlink"                         # Watch videos in mpv.
brew "yt-dlp"                             # Youtube Downloader.
