#! /bin/zsh

# Use homebrew autocompletion
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

# Enable fzf autocompletion
if type "fzf" &>/dev/null
then
    source <(fzf --zsh)
fi

# Enable built in autocompletion
autoload -U compinit
compinit

# This appends the history file incrementally allowing shared history between
# terminal windows/tmux panes.
setopt INC_APPEND_HISTORY
HISTFILE=~/.history
HISTSIZE=50000

# Add local scripts to PATH
PATH="${HOME}/.bin:${PATH}"
PATH="${HOME}/.local/bin:${PATH}"
export PATH

# Use the Terminal to unlock GPG keys. Used for passwordstore.
TTY=$(tty)
export GPG_TTY=$TTY

export HOMEBREW_BUNDLE_FILE_GLOBAL="${HOME}/.config/homebrew/Brewfile"

# This reduces the timeout when sending multiple control characters to the
# terminal. I have it set this way so that I can start typing more quickly after
# changing tmux panes.
export KEYTIMEOUT=1

# Use vim style keybinds.
bindkey -v

# If I have to any of these out one more time I will lose my mind.
alias ll='ls -lahFG' # Is this compatible with gls?
alias brew='arch -arm64 brew' # Make homebrew use arm64 since I have no Intel

# BSD date doesn't have iso8601 output.
alias isodate='date -u +"%Y-%m-%dT%H:%M:%SZ"'

# Just some useful shorcuts
alias gg='git grep' # limit grep to files under version control.
alias vi='vim'
alias v='vim'
alias t='tmux'
alias lynx='lynx -vikeys'

# Starship is the least worst prompt I've seen.
if type "starship" > /dev/null
then
    eval "$(starship init zsh)"
fi

# ls colors for various commands
if type "vivid" > /dev/null
then
    LS_COLORS=$(vivid generate solarized-light)
    export LS_COLORS
fi
