#!/bin/zsh
# shellcheck shell=bash

echo "### Linking Goodsprings Dotfiles ###"
ln -sf "${PWD}/machines/goodsprings/.Brewfile" "${HOME}/.Brewfile"
ln -sf "${PWD}/machines/goodsprings/.zprofile.local" "${HOME}/.zprofile.local"
ln -sf "${PWD}/machines/goodsprings/.zshrc.local" "${HOME}/.zshrc.local"
ln -sf "${PWD}/machines/goodsprings/.gitconfig" "${HOME}/.gitconfig"
ln -sf "${PWD}/machines/goodsprings/.gitignore_global" \
       "${HOME}/.gitignore_global"

mkdir -p "${HOME}/.config"
rm -rf  "${HOME}/.config/streamlink"
ln -sf "${PWD}/machines/goodsprings/streamlink" "${HOME}/.config/streamlink"

rm -rf  "${HOME}/.doom.d"
ln -sf "${PWD}/machines/goodsprings/.doom.d" "${HOME}/.doom.d"

if ! command -v brew > /dev/null
then
  echo "### Installing Homebrew ###"
  /bin/bash -c \
    "$( \
      curl -fsSL \
      https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh \
    )"
else
  echo "### Brew detected, skipping install ###"
fi

echo "### Syncing Homebrew packages ###"
brew bundle --global --clean

if [ -f ~/.emacs.d/.doomrc ]
then
  echo "### Doom detected, skipping install ###"
else
  echo "### Installing Doom ###" 
  rm -rf ~/.emacs.d
  git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
  ~/.emacs.d/bin/doom install
fi

echo "### Syncing Doom ###"
~/.emacs.d/bin/doom sync

echo "### Regenerating Doom env ###"
~/.emacs.d/bin/doom env
