#!/bin/sh

echo "### Linking Goodsprings Dotfiles ###"
ln -sf "${PWD}/machines/goodsprings/.Brewfile" "${HOME}/.Brewfile"

if ! command -v brew > /dev/null
then
  echo "### Installing Homebrew ###"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "### Brew detected, skipping install ###"
fi

echo "### Syncing Homebrew packages###"
brew bundle --global --clean
