set nocompatible

set number
set ruler
set showmode
set laststatus=2
set nowrap

syntax enable
set background=dark

filetype plugin on
set autoindent
set smartindent
set smarttab

set backupcopy=yes
set clipboard=unnamed
set mouse=a

call plug#begin()

" Uses ANSI colorscheme
" https://github.com/jeffkreeftmeijer/vim-dim
colorscheme dim

" Let a .editorconfig file set tabs/spaces, etc.
Plug 'editorconfig/editorconfig-vim'

" Let vim automatically determine file settings absent editorconfig
Plug 'tpope/vim-sleuth'

" Surround text objects with a character.
Plug 'tpope/vim-surround'

" Add command to comment lines (gc).
Plug 'tpope/vim-commentary'

" Allow plugins (surround) to repeat with .
Plug 'tpope/vim-repeat'

" Add indent levels as text objects.
Plug 'michaeljsmith/vim-indent-object'

" Add additonal predicates for text objects: next and last, as well as a few new
" text objects like text delimeters (, and |).
Plug 'wellle/targets.vim'

" Align a text object around a given character.
Plug 'junegunn/vim-easy-align'
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)

" Auto close parentheses
Plug 'cohama/lexima.vim'

" Auto close tags
Plug 'alvan/vim-closetag'

" File tree
Plug 'preservim/nerdtree'

" Git support
Plug 'tpope/vim-fugitive'

" Git line changes
Plug 'airblade/vim-gitgutter'

" Syntax and format checker
Plug 'dense-analysis/ale'

" FZF integration
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

call plug#end()
