#! /bin/sh

# Designed to install developer tools inside a debian based docker image.

# Install Developer tools
echo "### Installing Packages ###"
sudo apt-get update \
  && sudo apt-get -y install \
    vim \
    tmux \
    lynx \
    entr \
    shellcheck \
    universal-ctags \
    jq

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
